import { PlanConfig, PlanTier } from "@/types";

export const SUBSCRIPTION_PLANS: Record<PlanTier, PlanConfig> = {
  BASIC: {
    id: "BASIC",
    title: "Starter",
    price: 150,
    currency: "INR",
    interval: "monthly",
    description: "Essential AI, Image & PDF toolkit for students and hobbyists.",
    aiLimit: 20,
    fileUploadLimitMb: 15,
    videoLimitMin: 5,
    storageLimitMb: 500,
    features: [
      "Access to Basic AI Content Tools (20 requests/mo)",
      "Standard Image Resizer, Compressor & Cropper",
      "Essential PDF Merge, Split & Compress",
      "All Developer & Productivity Utilities",
      "Max file upload size: 15MB",
      "500MB cloud workspace storage",
      "Standard email support",
    ],
  },
  PRO: {
    id: "PRO",
    title: "Pro Creator",
    price: 450,
    currency: "INR",
    interval: "monthly",
    description: "Designed for content creators, freelancers, and growing builders.",
    aiLimit: 100,
    fileUploadLimitMb: 75,
    videoLimitMin: 20,
    storageLimitMb: 5000,
    popular: true,
    features: [
      "Unlimited AI Requests per month",
      "AI Background Remover & 4x Image Upscaler",
      "Video Compressor, Trimmer & GIF Converter",
      "All Advanced PDF Extraction & Reordering Tools",
      "Higher upload limit: 75MB",
      "5GB persistent cloud storage",
      "Faster background job queue priority",
      "Priority customer assistance",
    ],
  },
  PREMIUM: {
    id: "PREMIUM",
    title: "Enterprise",
    price: 1200,
    currency: "INR",
    interval: "monthly",
    description: "Uncapped power, maximum throughput, and full studio capabilities.",
    aiLimit: 500,
    fileUploadLimitMb: 250,
    videoLimitMin: 60,
    storageLimitMb: 25000,
    features: [
      "500+ Advanced AI Generation requests per month",
      "Full access to all 50+ tools in every category",
      "Full Video Suite with Audio Extraction & Subtitles",
      "Maximum file upload size: 250MB",
      "25GB high-speed cloud project storage",
      "Top-tier priority processing server pipeline",
      "Direct developer API access & export",
      "24/7 dedicated support",
    ],
  },
};
