import { ToolDefinition } from "@/types";

export const TOOLS_REGISTRY: ToolDefinition[] = [
  // ==========================================
  // 1. AI CONTENT TOOLS (15 tools)
  // ==========================================
  {
    slug: "ai-content-writer",
    name: "AI Content Writer",
    category: "AI",
    description: "Generate structured, engaging content by specifying topic, tone, length, and target audience.",
    planRequired: "BASIC",
    icon: "PenTool",
    isFeatured: true,
    tags: ["writing", "ai", "content", "marketing"],
    apiEndpoint: "/api/tools/ai/content-writer",
  },
  {
    slug: "blog-generator",
    name: "Blog Post Generator",
    category: "AI",
    description: "Turn keywords and topics into high-ranking, outline-structured blog posts with headings.",
    planRequired: "BASIC",
    icon: "BookOpen",
    isFeatured: true,
    tags: ["blog", "seo", "longform"],
    apiEndpoint: "/api/tools/ai/blog-generator",
  },
  {
    slug: "article-writer",
    name: "Long-form Article Writer",
    category: "AI",
    description: "Craft thorough, research-oriented articles with introduction, body arguments, and conclusion.",
    planRequired: "PRO",
    icon: "FileText",
    tags: ["article", "essay", "research"],
    apiEndpoint: "/api/tools/ai/article-writer",
  },
  {
    slug: "product-description-generator",
    name: "Product Description Generator",
    category: "AI",
    description: "High-converting eCommerce product copy highlighting features, benefits, and call to actions.",
    planRequired: "BASIC",
    icon: "ShoppingBag",
    tags: ["ecommerce", "sales", "copywriting"],
    apiEndpoint: "/api/tools/ai/product-description",
  },
  {
    slug: "email-writer",
    name: "Professional Email Writer",
    category: "AI",
    description: "Generate sales pitches, customer support replies, professional follow-ups, and newsletters.",
    planRequired: "BASIC",
    icon: "Mail",
    tags: ["email", "communication", "sales"],
    apiEndpoint: "/api/tools/ai/email-writer",
  },
  {
    slug: "social-media-captions",
    name: "Social Media Caption Generator",
    category: "AI",
    description: "Catchy captions with trending hashtags for Instagram, LinkedIn, X, and Facebook.",
    planRequired: "BASIC",
    icon: "Share2",
    tags: ["social", "instagram", "linkedin", "twitter"],
    apiEndpoint: "/api/tools/ai/social-captions",
  },
  {
    slug: "youtube-title-generator",
    name: "YouTube Title Generator",
    category: "AI",
    description: "High-CTR, viral YouTube video title suggestions based on audience psychology and keywords.",
    planRequired: "BASIC",
    icon: "PlaySquare",
    tags: ["youtube", "video", "marketing"],
    apiEndpoint: "/api/tools/ai/youtube-title",
  },
  {
    slug: "youtube-description-generator",
    name: "YouTube Description & Tags",
    category: "AI",
    description: "Complete YouTube video descriptions packed with timestamps, CTAs, tags, and hashtags.",
    planRequired: "BASIC",
    icon: "Video",
    tags: ["youtube", "seo", "tags"],
    apiEndpoint: "/api/tools/ai/youtube-description",
  },
  {
    slug: "seo-keyword-generator",
    name: "SEO Keyword Generator",
    category: "AI",
    description: "Generate targeted semantic keyword ideas and content clusters for your niche.",
    planRequired: "PRO",
    icon: "Key",
    tags: ["seo", "keywords", "search"],
    apiEndpoint: "/api/tools/ai/seo-keywords",
  },
  {
    slug: "grammar-checker",
    name: "Grammar & Spell Checker",
    category: "AI",
    description: "Detect grammatical errors, spelling typos, and get contextual sentence improvements.",
    planRequired: "BASIC",
    icon: "CheckCircle",
    tags: ["proofreading", "grammar", "editing"],
    apiEndpoint: "/api/tools/ai/grammar-checker",
  },
  {
    slug: "text-summarizer",
    name: "Smart Text Summarizer",
    category: "AI",
    description: "Condense long reports, essays, or transcripts into short, medium, or detailed bullet summaries.",
    planRequired: "BASIC",
    icon: "AlignLeft",
    tags: ["summary", "reading", "bulletpoints"],
    apiEndpoint: "/api/tools/ai/text-summarizer",
  },
  {
    slug: "paraphraser",
    name: "Sentence & Text Paraphraser",
    category: "AI",
    description: "Rewrite sentences and paragraphs across formal, casual, simple, or creative tones.",
    planRequired: "BASIC",
    icon: "Repeat",
    tags: ["rewrite", "paraphrase", "clarity"],
    apiEndpoint: "/api/tools/ai/paraphraser",
  },
  {
    slug: "translator",
    name: "Multi-Language Translator",
    category: "AI",
    description: "Accurate, culturally nuanced translations across 50+ international languages.",
    planRequired: "BASIC",
    icon: "Languages",
    tags: ["translation", "language", "multilingual"],
    apiEndpoint: "/api/tools/ai/translator",
  },
  {
    slug: "script-writer",
    name: "Video & Shorts Script Writer",
    category: "AI",
    description: "Full scene-by-scene video scripts with audio cues, hook, body, and CTA.",
    planRequired: "PRO",
    icon: "Clapperboard",
    tags: ["script", "reels", "tiktok", "youtube"],
    apiEndpoint: "/api/tools/ai/script-writer",
  },
  {
    slug: "resume-generator",
    name: "AI Resume & CV Generator",
    category: "AI",
    description: "Transform your raw work history into polished, ATS-optimized professional resume bullet points.",
    planRequired: "PRO",
    icon: "FileUser",
    tags: ["career", "resume", "cv", "jobs"],
    apiEndpoint: "/api/tools/ai/resume-generator",
  },
  {
    slug: "ai-code-auditor",
    name: "Code Reviewer & Bug Fixer",
    category: "AI",
    description: "Scan source code to find bugs, security issues, and get instant code fixes.",
    planRequired: "PRO",
    icon: "Code2",
    isFeatured: true,
    tags: ["code", "security", "refactor", "developer", "audit"],
    apiEndpoint: "/api/tools/ai/code-auditor",
  },
  {
    slug: "ai-sql-builder",
    name: "Text to SQL Generator",
    category: "AI",
    description: "Convert plain English instructions into clean, optimized SQL database queries.",
    planRequired: "PRO",
    icon: "Database",
    tags: ["sql", "database", "postgres", "queries"],
    apiEndpoint: "/api/tools/ai/sql-builder",
  },
  {
    slug: "ai-sales-pitch",
    name: "Sales Pitch & Cold Email Writer",
    category: "AI",
    description: "Create high-converting sales pitches, cold emails, and outreach messages.",
    planRequired: "PRO",
    icon: "Send",
    tags: ["sales", "b2b", "email", "cold-outreach", "linkedin"],
    apiEndpoint: "/api/tools/ai/sales-pitch",
  },
  {
    slug: "ai-pitchdeck-generator",
    name: "Startup Pitch Deck Creator",
    category: "AI",
    description: "Generate a complete 10-slide startup pitch deck outline and investor memo.",
    planRequired: "PRO",
    icon: "Presentation",
    isFeatured: true,
    tags: ["startup", "pitchdeck", "vc", "fundraising", "investors"],
    apiEndpoint: "/api/tools/ai/pitchdeck-generator",
  },
  {
    slug: "ai-voiceover-script",
    name: "Voiceover Script Writer",
    category: "AI",
    description: "Write voiceover, podcast, and commercial ad scripts with timing marks.",
    planRequired: "PRO",
    icon: "Mic",
    tags: ["voiceover", "podcast", "speech", "tts", "elevenlabs"],
    apiEndpoint: "/api/tools/ai/voiceover-script",
  },
  {
    slug: "nano-banana-image-studio",
    name: "AI Photo Studio",
    category: "AI",
    description: "Generate ultra-high-resolution photorealistic images and digital art from text prompts.",
    planRequired: "PRO",
    icon: "Sparkles",
    isFeatured: true,
    tags: ["image-generation", "nano-banana", "diffusion", "photorealistic", "art"],
    apiEndpoint: "/api/tools/ai/nano-banana-studio",
  },

  // ==========================================
  // 2. IMAGE TOOLS (14 tools + AI Image Gen)
  // ==========================================
  {
    slug: "background-remover",
    name: "AI Background Remover",
    category: "IMAGE",
    description: "Isolate subjects and download clean transparent PNG files with edge precision.",
    planRequired: "PRO",
    icon: "Scissors",
    isFeatured: true,
    tags: ["removebg", "transparent", "cutout"],
    apiEndpoint: "/api/tools/image/background-remover",
  },
  {
    slug: "background-changer",
    name: "Background Changer",
    category: "IMAGE",
    description: "Replace image background with solid colors, clean studio backdrops, or custom uploads.",
    planRequired: "PRO",
    icon: "Palette",
    tags: ["backdrop", "studio", "e-commerce"],
    apiEndpoint: "/api/tools/image/background-changer",
  },
  {
    slug: "image-resizer",
    name: "Image Resizer & Social Presets",
    category: "IMAGE",
    description: "Resize images to custom dimensions or standard presets (Instagram, YouTube, Twitter/X, LinkedIn).",
    planRequired: "BASIC",
    icon: "Scaling",
    tags: ["resize", "dimensions", "aspect-ratio"],
    apiEndpoint: "/api/tools/image/resizer",
  },
  {
    slug: "image-compressor",
    name: "Lossless Image Compressor",
    category: "IMAGE",
    description: "Drastically reduce image file sizes while preserving sharp visual fidelity.",
    planRequired: "BASIC",
    icon: "Minimize2",
    tags: ["compress", "optimize", "web-ready"],
    apiEndpoint: "/api/tools/image/compressor",
  },
  {
    slug: "image-converter",
    name: "Image Format Converter",
    category: "IMAGE",
    description: "Batch convert between PNG, JPG, and high-efficiency WEBP formats in high quality.",
    planRequired: "BASIC",
    icon: "RefreshCw",
    tags: ["png", "jpg", "webp", "convert"],
    apiEndpoint: "/api/tools/image/converter",
  },
  {
    slug: "image-cropper",
    name: "Precision Image Cropper",
    category: "IMAGE",
    description: "Crop photos with aspect ratios: Freeform, 1:1, 16:9, 9:16, 4:3, and circular.",
    planRequired: "BASIC",
    icon: "Crop",
    tags: ["crop", "cut", "aspect-ratio"],
    apiEndpoint: "/api/tools/image/cropper",
  },
  {
    slug: "image-upscaler",
    name: "AI Image Upscaler (2x / 4x)",
    category: "IMAGE",
    description: "Upscale low-resolution photos to crisp high definition using deep neural networks.",
    planRequired: "PRO",
    icon: "ZoomIn",
    isFeatured: true,
    tags: ["upscale", "super-resolution", "ai-enhancement"],
    apiEndpoint: "/api/tools/image/upscaler",
  },
  {
    slug: "image-enhancer",
    name: "Photo Enhancer",
    category: "IMAGE",
    description: "Fine-tune brightness, contrast, saturation, sharpness, and exposure levels with live preview.",
    planRequired: "BASIC",
    icon: "Sliders",
    tags: ["enhance", "color", "balance"],
    apiEndpoint: "/api/tools/image/enhancer",
  },
  {
    slug: "image-blur-tool",
    name: "Image Blur Tool",
    category: "IMAGE",
    description: "Apply gaussian blur with customizable intensity for privacy, backdrops, or artistic focus.",
    planRequired: "BASIC",
    icon: "Sparkle",
    tags: ["blur", "privacy", "depth"],
    apiEndpoint: "/api/tools/image/blur",
  },
  {
    slug: "image-sharpener",
    name: "Image Sharpener",
    category: "IMAGE",
    description: "Enhance edge clarity and recover crisp details on soft photos.",
    planRequired: "BASIC",
    icon: "Eye",
    tags: ["sharpen", "clarity", "details"],
    apiEndpoint: "/api/tools/image/sharpener",
  },
  {
    slug: "add-text-to-image",
    name: "Add Text & Typography to Image",
    category: "IMAGE",
    description: "Overlay custom text with fonts, styling, sizing, rotation, and alignment.",
    planRequired: "BASIC",
    icon: "Type",
    tags: ["text", "overlay", "caption", "watermark"],
    apiEndpoint: "/api/tools/image/add-text",
  },
  {
    slug: "image-filters",
    name: "Cinematic Image Filters",
    category: "IMAGE",
    description: "Apply instant presets: Vintage, Black & White, Warm Sun, Cool Cyan, and High Contrast.",
    planRequired: "BASIC",
    icon: "Film",
    tags: ["filters", "vintage", "bw", "cinematic"],
    apiEndpoint: "/api/tools/image/filters",
  },
  {
    slug: "passport-photo-maker",
    name: "Passport Photo Creator",
    category: "IMAGE",
    description: "Crop and scale photos to standard passport and visa specifications with white backdrop.",
    planRequired: "BASIC",
    icon: "UserSquare2",
    tags: ["passport", "id-card", "official-photo"],
    apiEndpoint: "/api/tools/image/passport-photo",
  },
  {
    slug: "collage-maker",
    name: "Grid Collage Maker",
    category: "IMAGE",
    description: "Combine multiple photos into neat grid layouts with custom borders and spacing.",
    planRequired: "BASIC",
    icon: "LayoutGrid",
    tags: ["collage", "grid", "montage"],
    apiEndpoint: "/api/tools/image/collage-maker",
  },
  {
    slug: "image-watermark-studio",
    name: "Add Watermark to Photo",
    category: "IMAGE",
    description: "Add custom text, copyright stamps, or diagonal watermarks to photos.",
    planRequired: "PRO",
    icon: "ShieldCheck",
    tags: ["watermark", "copyright", "branding", "protection"],
    apiEndpoint: "/api/tools/image/watermark-studio",
  },
  {
    slug: "watermark-remover",
    name: "Remove Watermark from Photo",
    category: "IMAGE",
    description: "Select or mark any watermark, logo, or text on a photo to blur or remove it completely.",
    planRequired: "PRO",
    icon: "Eraser",
    isFeatured: true,
    tags: ["watermark-remover", "delogo", "inpaint", "cleanup", "retouch"],
    apiEndpoint: "/api/tools/image/watermark-remover",
  },
  {
    slug: "ai-image-generator",
    name: "AI Image Generator",
    category: "AI",
    description: "Generate photorealistic artwork, illustrations, and concept graphics from text prompts.",
    planRequired: "PREMIUM",
    icon: "Wand2",
    isFeatured: true,
    tags: ["image-generation", "diffusion", "art"],
    apiEndpoint: "/api/tools/ai/image-generator",
  },

  // ==========================================
  // 3. VIDEO & AUDIO TOOLS (12 tools)
  // ==========================================
  {
    slug: "video-compressor",
    name: "Video Compressor",
    category: "VIDEO",
    description: "Shrink video file sizes while retaining crystal clear video quality.",
    planRequired: "PRO",
    icon: "FileArchive",
    isFeatured: true,
    tags: ["video", "compress", "mp4"],
    apiEndpoint: "/api/tools/video/compressor",
  },
  {
    slug: "video-converter",
    name: "Video Format Converter",
    category: "VIDEO",
    description: "Convert video files between MP4, WebM, MOV, and AVI formats.",
    planRequired: "PRO",
    icon: "RefreshCw",
    tags: ["video", "convert", "mp4", "webm"],
    apiEndpoint: "/api/tools/video/converter",
  },
  {
    slug: "video-trimmer",
    name: "Video Trimmer & Cutter",
    category: "VIDEO",
    description: "Set precise start and end times to cut out unnecessary video segments.",
    planRequired: "BASIC",
    icon: "Scissors",
    tags: ["trim", "cut", "clip"],
    apiEndpoint: "/api/tools/video/trimmer",
  },
  {
    slug: "video-cropper",
    name: "Video Cropper & Aspect Ratio",
    category: "VIDEO",
    description: "Crop videos to 1:1, 16:9, 9:16 (TikTok/Reels/Shorts), and 4:3 dimensions.",
    planRequired: "PRO",
    icon: "Crop",
    tags: ["crop", "aspect", "reels", "tiktok"],
    apiEndpoint: "/api/tools/video/cropper",
  },
  {
    slug: "video-merger",
    name: "Merge Videos",
    category: "VIDEO",
    description: "Combine multiple video clips into one single video file.",
    planRequired: "PRO",
    icon: "Layers",
    tags: ["merge", "join", "stitch"],
    apiEndpoint: "/api/tools/video/merger",
  },
  {
    slug: "video-to-gif",
    name: "Video to Animated GIF",
    category: "VIDEO",
    description: "Transform video clips into lightweight, looping animated GIF stickers.",
    planRequired: "BASIC",
    icon: "ImagePlay",
    tags: ["gif", "animation", "meme"],
    apiEndpoint: "/api/tools/video/video-to-gif",
  },
  {
    slug: "gif-to-video",
    name: "GIF to MP4 Video Converter",
    category: "VIDEO",
    description: "Convert looping GIFs into smooth, high-compatibility MP4 video format.",
    planRequired: "BASIC",
    icon: "Video",
    tags: ["gif-to-video", "mp4"],
    apiEndpoint: "/api/tools/video/gif-to-video",
  },
  {
    slug: "extract-audio",
    name: "Extract Audio from Video",
    category: "VIDEO",
    description: "Extract clean audio sound tracks from video files in MP3 or WAV format.",
    planRequired: "BASIC",
    icon: "Music",
    tags: ["audio", "extract", "mp3", "soundtrack"],
    apiEndpoint: "/api/tools/video/extract-audio",
  },
  {
    slug: "add-subtitles",
    name: "Add Subtitles to Video",
    category: "VIDEO",
    description: "Embed subtitles and captions directly into your video files.",
    planRequired: "PRO",
    icon: "Subtitles",
    tags: ["subtitles", "srt", "captions"],
    apiEndpoint: "/api/tools/video/add-subtitles",
  },
  {
    slug: "video-speed-controller",
    name: "Change Video Speed",
    category: "VIDEO",
    description: "Accelerate or slow down video footage (0.5x, 1x, 1.25x, 1.5x, 2x).",
    planRequired: "BASIC",
    icon: "FastForward",
    tags: ["speed", "slowmo", "timelapse"],
    apiEndpoint: "/api/tools/video/speed-controller",
  },
  {
    slug: "mute-video",
    name: "Mute Video",
    category: "VIDEO",
    description: "Remove the audio track entirely from any video file to make it silent.",
    planRequired: "BASIC",
    icon: "VolumeX",
    tags: ["mute", "silent-video"],
    apiEndpoint: "/api/tools/video/mute",
  },
  {
    slug: "video-resolution-converter",
    name: "Change Video Resolution",
    category: "VIDEO",
    description: "Transcode video files to standard resolutions: 480p, 720p, and 1080p.",
    planRequired: "PRO",
    icon: "Tv",
    tags: ["resolution", "1080p", "720p"],
    apiEndpoint: "/api/tools/video/resolution-converter",
  },
  {
    slug: "ai-video-generator",
    name: "AI Video Generator",
    category: "VIDEO",
    description: "Generate 10-second cinematic video clips from text prompts, photos, or links with smooth camera motion.",
    planRequired: "PRO",
    icon: "Sparkles",
    isFeatured: true,
    tags: ["ai-video", "10-second", "video-generation", "cinematic", "motion", "reels"],
    apiEndpoint: "/api/tools/video/ai-generator",
  },

  // ==========================================
  // 4. PDF TOOLS (10 tools)
  // ==========================================
  {
    slug: "pdf-merge",
    name: "Merge PDF Files",
    category: "PDF",
    description: "Combine multiple PDF documents into one single organized PDF file.",
    planRequired: "BASIC",
    icon: "FilePlus",
    isFeatured: true,
    tags: ["pdf", "merge", "combine"],
    apiEndpoint: "/api/tools/pdf/merge",
  },
  {
    slug: "pdf-split",
    name: "Split & Extract PDF",
    category: "PDF",
    description: "Split PDF pages into separate documents or extract custom page intervals.",
    planRequired: "BASIC",
    icon: "FileMinus",
    tags: ["pdf", "split", "extract-pages"],
    apiEndpoint: "/api/tools/pdf/split",
  },
  {
    slug: "pdf-compress",
    name: "Compress & Optimize PDF",
    category: "PDF",
    description: "Reduce PDF document file size for easy emailing while maintaining crisp typography.",
    planRequired: "BASIC",
    icon: "FileArchive",
    tags: ["pdf", "compress", "shrink"],
    apiEndpoint: "/api/tools/pdf/compress",
  },
  {
    slug: "image-to-pdf",
    name: "Images to PDF Converter",
    category: "PDF",
    description: "Convert JPG, PNG, and WEBP photos into a clean, multi-page PDF document.",
    planRequired: "BASIC",
    icon: "FileImage",
    tags: ["images-to-pdf", "convert"],
    apiEndpoint: "/api/tools/pdf/image-to-pdf",
  },
  {
    slug: "pdf-to-image",
    name: "PDF to High-Res Images",
    category: "PDF",
    description: "Render and export every page of a PDF document as high-resolution PNG or JPG images.",
    planRequired: "BASIC",
    icon: "FileDown",
    tags: ["pdf-to-image", "render"],
    apiEndpoint: "/api/tools/pdf/pdf-to-image",
  },
  {
    slug: "pdf-text-extractor",
    name: "Extract Text from PDF",
    category: "PDF",
    description: "Extract raw, unformatted or structured text content from PDF pages.",
    planRequired: "BASIC",
    icon: "FileSearch",
    tags: ["pdf", "text-extraction", "ocr"],
    apiEndpoint: "/api/tools/pdf/extract-text",
  },
  {
    slug: "pdf-rotate",
    name: "Rotate PDF Pages",
    category: "PDF",
    description: "Rotate upside-down or sideways pages clockwise or counter-clockwise (90°, 180°, 270°).",
    planRequired: "BASIC",
    icon: "RotateCw",
    tags: ["rotate", "orientation"],
    apiEndpoint: "/api/tools/pdf/rotate",
  },
  {
    slug: "pdf-page-reorder",
    name: "Reorder & Rearrange PDF Pages",
    category: "PDF",
    description: "Drag-and-drop visual page preview to reorder, delete, and duplicate pages.",
    planRequired: "BASIC",
    icon: "ArrowUpDown",
    tags: ["reorder", "organize"],
    apiEndpoint: "/api/tools/pdf/reorder",
  },
  {
    slug: "pdf-form-filling",
    name: "Fill PDF Forms",
    category: "PDF",
    description: "Input and save data into fillable AcroForm and PDF document text fields.",
    planRequired: "PRO",
    icon: "FileCheck",
    tags: ["forms", "acroform", "fill"],
    apiEndpoint: "/api/tools/pdf/form-fill",
  },
  {
    slug: "pdf-metadata-viewer",
    name: "PDF Metadata Inspector",
    category: "PDF",
    description: "Inspect title, author, producer, creation date, modification history, and PDF version.",
    planRequired: "BASIC",
    icon: "Info",
    tags: ["metadata", "inspector"],
    apiEndpoint: "/api/tools/pdf/metadata",
  },
  {
    slug: "pdf-watermark-stamp",
    name: "Add Watermark to PDF",
    category: "PDF",
    description: "Add custom text, stamps, or diagonal watermarks across all PDF pages.",
    planRequired: "PRO",
    icon: "Stamp",
    tags: ["pdf", "watermark", "confidential", "stamp"],
    apiEndpoint: "/api/tools/pdf/watermark-stamp",
  },
  {
    slug: "pdf-password-protect",
    name: "Lock PDF with Password",
    category: "PDF",
    description: "Protect confidential PDF files with a password to prevent unauthorized viewing.",
    planRequired: "PRO",
    icon: "Lock",
    tags: ["pdf", "security", "encrypt", "password"],
    apiEndpoint: "/api/tools/pdf/password-protect",
  },
  {
    slug: "pdf-unlocker",
    name: "Unlock PDF (Remove Password)",
    category: "PDF",
    description: "Remove passwords and restrictions from locked PDF files to view and print freely.",
    planRequired: "PRO",
    icon: "Unlock",
    isFeatured: true,
    tags: ["pdf", "unlock", "decrypt", "remove-password", "permissions"],
    apiEndpoint: "/api/tools/pdf/unlocker",
  },

  // ==========================================
  // 5. DEVELOPER TOOLS (6 tools)
  // ==========================================
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    category: "DEVELOPER",
    description: "Parse, format with indentation, validate syntax, and minify complex JSON objects.",
    planRequired: "BASIC",
    icon: "Code",
    tags: ["json", "format", "minify", "developer"],
    apiEndpoint: "/api/tools/dev/json-formatter",
  },
  {
    slug: "base64-tool",
    name: "Base64 Encoder / Decoder",
    category: "DEVELOPER",
    description: "Encode strings and binary files to Base64 and decode Base64 data back to plain text.",
    planRequired: "BASIC",
    icon: "Binary",
    tags: ["base64", "decode", "encode"],
    apiEndpoint: "/api/tools/dev/base64",
  },
  {
    slug: "url-encoder",
    name: "URL Encoder & Decoder",
    category: "DEVELOPER",
    description: "Safely encode and decode URI components and query string parameters.",
    planRequired: "BASIC",
    icon: "Link",
    tags: ["url", "uri", "percent-encoding"],
    apiEndpoint: "/api/tools/dev/url-encode",
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    category: "DEVELOPER",
    description: "Generate strong, secure passwords with custom length, symbols, and numbers.",
    planRequired: "BASIC",
    icon: "ShieldAlert",
    tags: ["security", "password", "crypto"],
    apiEndpoint: "/api/tools/dev/password-generator",
  },
  {
    slug: "regex-studio",
    name: "Regex Tester & Generator",
    category: "DEVELOPER",
    description: "Test regular expressions live against sample text and generate regex patterns easily.",
    planRequired: "PRO",
    icon: "Code",
    isFeatured: true,
    tags: ["regex", "regexp", "developer", "pattern", "matching"],
    apiEndpoint: "/api/tools/dev/regex-studio",
  },
  {
    slug: "jwt-debugger",
    name: "JWT Token Decoder",
    category: "DEVELOPER",
    description: "Decode and inspect JSON Web Tokens (JWT) payload, headers, and expiration dates.",
    planRequired: "PRO",
    icon: "KeyRound",
    tags: ["jwt", "tokens", "auth", "security", "developer"],
    apiEndpoint: "/api/tools/dev/jwt-debugger",
  },

  // ==========================================
  // 6. PRODUCTIVITY & UTILITY TOOLS (6 tools)
  // ==========================================
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    category: "PRODUCTIVITY",
    description: "Create high-resolution QR codes for websites, text, and Wi-Fi networks.",
    planRequired: "BASIC",
    icon: "QrCode",
    tags: ["qr", "generator", "barcodes"],
    apiEndpoint: "/api/tools/productivity/qr-code",
  },
  {
    slug: "qr-code-scanner",
    name: "QR Code Scanner",
    category: "PRODUCTIVITY",
    description: "Upload any photo or screenshot of a QR code to read its URL or text content.",
    planRequired: "BASIC",
    icon: "Scan",
    tags: ["qr", "scanner", "decode"],
    apiEndpoint: "/api/tools/productivity/qr-scanner",
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    category: "PRODUCTIVITY",
    description: "Convert across Length, Weight, Temperature, Speed, and Digital Storage units.",
    planRequired: "BASIC",
    icon: "ArrowLeftRight",
    tags: ["units", "metrics", "conversion"],
    apiEndpoint: "/api/tools/productivity/unit-converter",
  },
  {
    slug: "color-picker",
    name: "Color Picker & Converter",
    category: "PRODUCTIVITY",
    description: "Pick colors and convert codes between HEX, RGB, and HSL formats.",
    planRequired: "BASIC",
    icon: "Pipette",
    tags: ["color", "hex", "rgb", "hsl"],
    apiEndpoint: "/api/tools/productivity/color-picker",
  },
  {
    slug: "text-case-converter",
    name: "Text Case Converter",
    category: "PRODUCTIVITY",
    description: "Convert text into UPPERCASE, lowercase, Title Case, camelCase, snake_case, and kebab-case.",
    planRequired: "BASIC",
    icon: "CaseSensitive",
    tags: ["case", "camelcase", "slugify"],
    apiEndpoint: "/api/tools/productivity/case-converter",
  },
  {
    slug: "safe-public-research",
    name: "Domain & Website Lookup",
    category: "UTILITIES",
    description: "Look up website DNS records, server IP, hosting provider, and domain info.",
    planRequired: "PRO",
    icon: "Globe",
    tags: ["whois", "dns", "domain", "network"],
    apiEndpoint: "/api/tools/utilities/public-research",
  },
  {
    slug: "ip-telecom-intel",
    name: "IP & Phone Number Lookup",
    category: "UTILITIES",
    description: "Look up IP address location and phone number country, carrier, and line details. (Admin restricted).",
    planRequired: "PRO",
    icon: "ShieldAlert",
    tags: ["intel", "ip", "telecom", "asn", "carrier", "admin"],
    apiEndpoint: "/api/tools/utilities/ip-telecom-intel",
    restrictedToAdmin: true,
  },
  {
    slug: "social-footprint-scanner",
    name: "Find Social Media Accounts",
    category: "UTILITIES",
    description: "Check which social media platforms a username is registered on, and inspect photo GPS location.",
    planRequired: "PRO",
    icon: "UserCheck",
    isFeatured: true,
    tags: ["osint", "privacy", "social-media", "exif", "security-audit"],
    apiEndpoint: "/api/tools/utilities/social-footprint",
  },
  {
    slug: "data-breach-scanner",
    name: "Check Leaked Email & Passwords",
    category: "UTILITIES",
    description: "Check if your email or phone number has been exposed in public data leaks and hacks.",
    planRequired: "PRO",
    icon: "Fingerprint",
    isFeatured: true,
    tags: ["data-breach", "pwned", "security", "leak-checker", "privacy"],
    apiEndpoint: "/api/tools/utilities/data-breach",
  },
];

